"""Initial migration

Revision ID: 4eb558896492
Revises: 
Create Date: 2026-06-29 06:09:24.771796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4eb558896492'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('location', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'companies', ['location'])
    op.add_column('jobs', sa.Column('salary', sa.Integer(), nullable=True))
    op.drop_column('jobs', 'Salary')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('Salary', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('jobs', 'salary')
    op.drop_constraint(None, 'companies', type_='unique')
    op.drop_column('companies', 'location')
    # ### end Alembic commands ###
